# Display
TW_THEME := portrait_hdpi
DEVICE_SCREEN_WIDTH := 1440
DEVICE_SCREEN_HEIGHT := 3200
TARGET_SCREEN_DENSITY := 560
TW_MAX_BRIGHTNESS := 4095
TW_DEFAULT_BRIGHTNESS := 2048
TW_BRIGHTNESS_PATH := "/sys/class/backlight/panel0-backlight/brightness"
TW_NO_SCREEN_BLANK := true
TW_NO_SCREEN_TIMEOUT := true
TW_USE_SERIALNO_PROPERTY_FOR_DEVICE_ID := true

# GPU Flags (Adreno 830 + VisionBoost D7)
TW_HAS_EXTRA_GPU_CHIP := true
TW_EXTRA_GPU_NAME := visionboost_d7
TW_EXTRA_GPU_MODULE_PATH := "/vendor/lib/modules/visionboost_d7.ko"
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TW_FORCE_USE_BUSYBOX := true

# Storage
TW_INCLUDE_NTFS_3G := true
TW_INCLUDE_FUSE_EXFAT := true
TW_INCLUDE_FUSE_NTFS := true
TW_USE_FSCRYPT_POLICY := 2
TW_EXCLUDE_APEX := true
TW_PREPARE_DATA_MEDIA_EARLY := true

# Crypto
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
TW_USE_FSCRYPT_POLICY := 2
BOARD_USES_METADATA_PARTITION := true

#
TW_HAS_EDL_MODE := true
TW_SUPPORT_INPUT_AIDL_HAPTICS := true
TW_LOAD_VENDOR_MODULES := "adsp_loader_dlkm.ko msm_drm.ko qti_battery_charger.ko"
TW_CUSTOM_CPU_TEMP_PATH := "/sys/class/thermal/thermal_zone50/temp"
TW_BATTERY_SYSFS_WAIT_SECONDS := 6

# UI
TW_EXTRA_LANGUAGES := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_TOOLBOX := true
TW_OZIP_DECRYPT_KEY := 0000
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_HAPTICS_TSPDRV := true

# Debug
TWRP_INCLUDE_LOGCAT := true
TARGET_USES_LOGD := true
TW_EXCLUDE_TWRPAPP := true
TW_EXCLUDE_PYTHON := true
TW_EXCLUDE_NANO := true
TW_EXCLUDE_BASH := true

# Custom
TW_DEVICE_VERSION := "Ultra_Rev1.0 by YourName"
TW_DELAY_TOUCH_INIT_MS := 2000
TW_Y_OFFSET := 80
TW_H_OFFSET := -80
TW_EXCLUDE_SUPERSU := true
TW_USE_NEW_MINADBD := true
